### PR TITLE
set up local environment

### PR DESCRIPTION
**Pull request by christianbraeunlich**
This PR attempts to solve #53.

### CODE REVIEW

**Comment by TheDoubleH** [comment]
using docker just for hugo, seems a little overkill for me, but to each his own.

I just have hugo installed locally on my windows 11 laptop.

That said, it was my plan to include a section on the site showing how to do that. - I would like to take a closer look at what You added.

**Comment by waldo1001** [comment]
I do think it makes sense, but from this info, I don't really get it to work (I'm quite stupid when it comes down to anything other than BC ;-) ).

**Comment by waldo1001** [comment]
I'm trying this out - but i'm getting:
image
Not sure what to do now 🤔

**Comment by waldo1001** [comment]
I set "experimantal" to true in my docker deamon...
image
then it doesn pull , but again an error:
image

I'm obviously using windows containers .. do I need Linux for this?

**Comment by TheDoubleH** [comment]
I simply downloaded the hugo executable (extended version). Placed it in c:\hugo (See https://gohugo.io/getting-started/installing#less-technical-users)

I added c:\Hugo to my PATH

https://gohugo.io/getting-started/installing#less-technical-users

I am now able to to do a `hugo serve -D --disableFastRender`

**Comment by christianbraeunlich** [comment]
Yes, "Switch to Linux containers" is a must. I need to make that stand out better in the documentation. There might also be an image for windows, I have to investigate.

I like @TheDoubleH 's setup more since the LiveReload function works as expected.

However I'm still trying to make this one work..
If I don't come up with a solution for this by the end of the year, I close this one and focus on the content instead,
as installing Hugo right away is the more solid approach and less time consuming 👍

**Comment by christianbraeunlich** [comment]
Hi, got it to work in the container with the **--poll** parameter. However, I am not satisfied with the solution, because the load on the CPU is just too big and will therefore join @TheDoubleH that it is the best solution to directly install Hugo. That's why I'm closing the PR.

**Pull request closed without merging**
